#+TITLE: Org-mode 学习总结
#+DATE: 2017-05-18
#+LAYOUT: post
#+TAGS: emacs org spacsmacs
#+CATEGORIES: emacs

* 什么是 Org-mode
  Org 是 emacs 中（现在也有独立的应用可以使用这种格式）的一个模式，用于通过纯文本格式快速高效的维护笔记、
TODO lists、和项目计划,他也是一个写作发布系统且支持嵌入程序源代码（当前这个博客正式通过 Org-mode 编写）。

** spacemacs 的快捷键调整比较大需要往这里看 [[https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bemacs/org][Spacemacs Org-mode 快捷键]]

* 文档结构
** 概要和标题

** 标题(Headlines)
   标题的格式如下
*** * 标题示例
**** ** 标题
**** ** 标题 2
***** *** 标题
****** **** 标题
******* ***** 标题
******** ****** 标题
       
** 标题操作
  orgmode 支持标题折叠，通过 tab 键可以切换标题的状态，通过 S-TAB 和 C-u TAB 可以在全文范围进行概览-内容-显示所有之间进行切换。
而在一个标题上面使用 tab 键则可以在折叠-显示子节点-显示子树之间切换。

注意 1：在 org-footnote-section 后命名的标题作为脚标被特别对待，这样的标题的子树静默被导出函数忽略。
注意 2：在 spacsmacs 中，Org-mode 的模式下 Org-mode 的相关快捷键通常以 C-c 或， 作为前缀。

** 标题间移动
   + C-c C-n 下一个标题
   + C-c C-p 上一个标题
   + C-c C-f 下一个同级标题
   + C-c C-b 上一个同级标题
   + C-c C-u 返回到上级标题
   
** 结构编辑
    + M-RET 在当前级别插入新标题，如果光标在一个常规列表项，将会建立一个新表项
    + M-S-RET 在当前标题同级插入一个新的 TODO 条目(在 spacemacs 中这个快捷键应该是 C-c C-x M)
    + TAB 在新空条目 在合理级别范围内调整条目
    + M-left/right 升/降当前标题的等级
    + M-S-left/right 升/降当前标题树（包括所有子孙节点）的等级
    + M-S-up/down 上下移动标题树（在同级前后子树间切换）(spacemacs 中干掉了这个快捷键）
    + C-c C-w 转接条目或区域到其他位置，类似于剪切黏贴然后切换条目级别 
    + C-x n s/w 局部编辑和取消当前子树
    
    上述操作在选中模式下批量操作所有选中区域的标题

** 稀疏树
    org-mode 一个非常重要的特性就是可以从概要树中抽取内容构建稀疏树，所以整个文档都被折叠了，
除了被抽取的内容和他的上级标题结构被展开显示（这个功能其实就是只展开满足筛选条件的内容，其他内容折叠)
    org-mode 包含了若干命令用于创建稀疏树，所有的命令都可以通过一个分发器（C-c /）访问
    C-c /    提示输入一个按键选择稀疏树的创建方式，比如 C-c /  r 提示输入一个正则表达式然后显示一个所有满足表达式的项的稀疏树
    其他的稀疏树命令基于 TODO 关键字，标签或者属性，这些将在文档的后面讨论

** 常规列表
    在概要树的条目中，手工格式列表可以提供更多的结构。它们提供了一个创建 checkbox 列表途径（section 5.6)
Org 支持编辑这样的列表和 HTML 导出器（Chapter 12）解析格式化它们。

    Org 中可以使用有序列表无序列表和描述列表
    + 无序列表使用'-'、'+'或者'*'作为条目符号
    + 有序列表则以'1.'或'1)'这样的符号开头
    + 描述列表使用'::'分隔术语和描述信息
  

列表中的所有条目必须拥有同样的缩进，一个条目在下一行有同样或更少缩进的时候该条目将会被结束。
一个列表在所有条目结束后关闭，或者在后面追加两个空行后关闭(M-RET 将不会集成这个级别的列表项前缀)

 
*** 示例
**** 指环王
     我喜欢的几幕
     1. 洛汗之战
     2. Eowyn 大战巫王
        + 我很喜欢 Miranda Otto
          + 下一级条目
        + 这个是我在这本书里面最喜欢的一处
        + 这行用于测试换行。
              这个是第二行
        + 后面又追加了一行
     电影里面重要的演员
        - Elijah Wook :: 饰演 Frodo
        - Sean Astin :: 饰演 Frodo 的朋友 Sam
**** 快捷键
     下面的命令在条目的第一行执行将作用于该条目
     + TAB 条目可以像标题那样被折叠
     + M-RET 在当前级别插入新条目
     + M-S-RET 插入一个新的 checkbox (没有找到 spacemacs 中对应的命令或快捷键)
     + M-S-up/down 上下移动条目和相关子条目（切换相同缩进的前后条目）
     + M-left/right 减增条目的缩进
     + C-c C-c 如果当前在一个 checkbox 条目则切换它的状态
     + C-c - 循环切换列表条目的前导符号（'-' '+' '*' '1.' '1)'）
** 脚注
    脚注被定义在一个有第 0 列（不允许有缩进）方括号括起来的脚注标记的段落里面，
    脚注引用就是一个简单的放在方括号里面的脚注标记，它被放在文本间，例如：
*** 示例 
    这个可以是文章的具体内容，这里[fn:1]插入了脚注
[fn:1] 这个是脚注的具体内容
*** 下面是用于处理脚注的命令
    C-c C-x f 脚注行为命令，如果光标在脚注上则跳转到定义，如果在定义上则跳转到第一个引用
              否则在当前增加脚注，增加前缀参数（C-u 数字）则会有一个菜单提供其他行为

    C-c C-c   在脚注定义和引用间跳转


** 表格 
   Org 携带了快速直观的表格编辑器。 类 Spreadsheet 的计算功能可以通过和 Emacs calc 插件结合来提供（参见 emacs Calculator 手册来获取更多细节）。
   Org 使通过朴素 ASCII 字符来构建表格变得很容易，每个第一个非空白字符为'|'的行被视为表格的一部分。'|'也是列分隔符，所以一个表格看上去应该是 下面这个样子。

      | Name  | Phone | Age |
      |-------+-------+-----|
      | Peter |  1234 |  17 |
      | Anna  |  4321 |  25 |

   每次你在表格里面按 TAB 或者 RET 或者 C-c C-c 的时候他都会被重新对齐。TAB 同时也会把光标挪向下一个字段。如果是在表格的最后或者在水平分割线(|---+---+---|)上
   则 TAB 会创建一个新行，表格的缩进由第一行决定，任何一个以'|-'开头的行被视为一个水平分隔符，将在下一次重新对齐表格时被扩展到整个表格的宽度，所以要创建上面的表格你只需要输入

      |Name|Phone|Age|
      |-

   然后按下 TAB 键对齐表格，之后就可以填充字段了，实际上更快的方法应该是输入
   |Name|Phone|Age 之后再输入 C-c RET

   当在字段中输入内容的时候 Org 特殊处理 DEL,BS 和所有字符键，插入和删除会避免其他字段的移动。当你使用 TAB，S-TAB 或者 RET 进入新字段的时候字段会被自动置空


